server.port =8080

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
hibernate.jdbc.time_zone=IST

database.driver=com.mysql.jdbc.Driver
database.user=root
database.url=jdbc:mysql://localhost:3306/steps?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
database.password=root